[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install", "npm install --prefix server"]

[phases.build]
cmds = ["echo 'Backend ready'"]

[start]
cmd = "node server/server.js"